#!/bin/bash

echo "=================================="
echo "   TWITCH BOT - QUICK START"
echo "=================================="
echo ""
echo "1. Install dependencies:"
echo "   npm install"
echo ""
echo "2. Copy environment template:"
echo "   cp .env.example .env"
echo ""
echo "3. Edit .env with your credentials:"
echo "   nano .env"
echo ""
echo "4. Test configuration:"
echo "   npm test"
echo ""
echo "5. Start the bot:"
echo "   npm start"
echo ""
echo "=================================="
echo "For detailed instructions, see:"
echo "- CLIENT_CHECKLIST.md (setup steps)"
echo "- SETUP_GUIDE.md (quick guide)"
echo "- README.md (full documentation)"
echo "=================================="
